### PR TITLE
add gzip support

### PR DESCRIPTION
**Pull request by pgehin-leansys**
Add gzip compression support to requests

### CODE REVIEW

**Comment by bojand** [comment]
Hello,

Thanks for the PR! 

I agree this would be useful; but perhaps can we make the compression feature opt-in rather than the default behaviour please. That way it would be backwards compatible with existing users, and can be explicitly turned on and off. I think this is especially pertinent  since the compressor API and the gzip encoding are still marked as experimental. We can use something like `--enable-compression` for a flag that would turn the parameter on. This would have to be added to the options and configs, documented, and ideally we would add tests.

**Comment by pgehin-leansys** [comment]
True. I will make the suggested changes.

**Comment by bojand** [comment]
Hello, thanks for taking the time to make these improvements! Sorry it took so long to review. A couple of suggestions:

Instead of doing if / else like so:
```go
if w.config.enableCompression {
	res, resErr = w.stub.InvokeRpc(ctx, w.mtd, inputs[inputIdx], grpc.UseCompressor(gzip.Name))
} else {
	res, resErr = w.stub.InvokeRpc(ctx, w.mtd, inputs[inputIdx])
}
```

It would be nicer to just use `grpc.CallOption` array as variadic argument. Something like this should work:
```go
var callOptions []grpc.CallOptions{}
if w.config.enableCompression {
	callOptions = append(callOptions, grpc.UseCompressor(gzip.Name))
}

res, resErr = w.stub.InvokeRpc(ctx, w.mtd, inputs[inputIdx], callOptions...)
```

In addition, we should add the documentation for the new flag to the [options](https://github.com/bojand/ghz/blob/master/www/docs/options.md) and [usage](https://github.com/bojand/ghz/blob/master/www/docs/usage.md) pages.

Thanks again.

**Comment by pgehin-leansys** [comment]
Will do.

**Pull request merged**
