### PR TITLE
Added feature to convert a field inside JSON to type []byte

### PR DESCRIPTION
**Pull request by anuj3918**
Hey,

I was running into the problem where a field inside my proto message was of type []byte. So I have added this flag to serialize a field inside the JSON provided.

I could have also taken an array of fields but then I found it to be an overkill.

Below is a screenshot of my use case. In the screenshot, you can see that I wanted to send "Value" field inside JSON as an object which will be having dynamic number of fields with dynamic datatypes. So I wanted to convert this into []byte for the server to handle.
screen shot 2018-10-05 at 6 23 55 pm

If you want to add/modify anything, please tell me. I'll be happy to make the changes.

Thanks
Anuj Gupta

### CODE REVIEW

**Comment by bojand** [comment]
Hello, thanks for the PR. Can you please explain the problem in more detail, and provide a sample proto file and JSON that demonstrates the issue. I want to understand the issue better and see why the current implementation does not work, and if there is a more appropriate approach to solve it. We would also need tests for the specific issue. It may be that if we use [golang/protobuf/jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb) it may be a more elegant solution, but that may require a slightly more complicated change.

Thanks,

Bojan

**Comment by anuj3918** [comment]
Thanks for the quick response Bojan. I will get back to you soon with more data, use case and test cases. Also, I will explore golang/protobuf/jsonpb as you have mentioned.

**Comment by anuj3918** [comment]
Hi Bojan,

I have modified the flag to take in comma separated field names inside JSON which are supposed to be converted into []byte. I checked "golang/protobuf/jsonpb" but could not get it to work for my case. I am adding the proto file and a details_server.go file similar to "ghz/internal/helloworld". That will help you understand my use case better. I thought of writing a test case too but was finding it troublesome to integrate it in the current project.

Use case explanation:
A server is storing details of a user.
A client wants to read some of those details of the user. He does not know the datatype of the detail and also doesn't know if the detail exists on the server or not. So the client sends a JSON which contains detail(key) and a value(default value) for every detail he wants to extract from the server. In case the detail is not present on the server, the server sends the default value back to the client.

Now, in this case, the client wants to send a dynamic JSON to the server. The number of fields inside the JSON and their datatypes are all dynamic. Also, the server sends back a JSON that can contain fields of any data type. So since we can't specify a contract, the client has to send all the data as []byte. 

Hence, I needed to convert a few fields inside the RequestMessage into []byte. Request message sent by client will look somewhat like this:
Message UserDetailsRequest{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;string Userid = 1;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bytes Properties = 2;
}
*Properties is a dynamic JSON of details client wants to read from server.

Please find the attached files [use_case.zip](https://github.com/bojand/ghz/files/2455844/use_case.zip)
1. details.proto
2. details.pb.go
3. details_server.go



It would be great of you can a test case for this change using the files I've provided as I am having trouble doing the same.

Best Regards,
Anuj

**Comment by bojand** [comment]
Hello, I've looked into this a little bit, and I believe a more appropriate generic solution would be to use  [golang/protobuf/jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb) for JSON unmarshaling of the input in general. Then in your specific scenario you could use one of the [well known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf), most likely [`Struct`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct) can work for you. For example some sample usage of the idea:

```proto
message UserDetailsRequest {
    string Userid = 1;
    google.protobuf.Struct Properties = 2;
}
```

```go
package main

import (
	"log"
	"strings"

	"github.com/golang/protobuf/jsonpb"
)

func main() {
	str := `{"Userid":"userId","Properties":{"foo":"bar","size":11,"nested":{"prop":true}}}`
	rdr := strings.NewReader(str)
	user := &UserDetailsRequest{}
	if err := jsonpb.Unmarshal(rdr, user); err != nil {
		log.Fatalln("Failed to parse user:", err)
	}

	log.Printf("PRINT:\n%+v\n", user)

	if user.Properties != nil {
		fields := user.Properties.GetFields()
		for k, v := range fields {
			log.Printf("k: %+s v: %+v\n", k, v.Kind)
		}
	}

	ma := jsonpb.Marshaler{}
	out, err := ma.MarshalToString(user)
	if err != nil {
		log.Fatalln("Failed to encode user data:", err)
	}

	log.Printf("JSON:\n%+v\n", out)
}
```

```sh
2018/10/16 11:04:04 PRINT:
Userid:"userId" Properties:<fields:<key:"foo" value:<string_value:"bar" > > fields:<key:"nested" value:<struct_value:<fields:<key:"prop" value:<bool_value:true > > > > > fields:<key:"size" value:<number_value:11 > > >
2018/10/16 11:04:04 k: size v: &{NumberValue:11}
2018/10/16 11:04:04 k: nested v: &{StructValue:fields:<key:"prop" value:<bool_value:true > > }
2018/10/16 11:04:04 k: foo v: &{StringValue:bar}
2018/10/16 11:04:04 JSON:
{"Userid":"userId","Properties":{"foo":"bar","nested":{"prop":true},"size":11}}
```
Note that the well-known types come with `protoc` so you just need to add it as an include to the compile, ie. something like `-I=/usr/bin/protoc-3.6.0/include`

I'll try and get a PR for `protobuf/jsonpb` soon.

**Comment by bojand** [comment]
Hello, further looking into this, and it seems this should already work fine with `ghz` if you use `Struct` as suggested. Example server:

```proto
syntax = "proto3";

package pbtypes;

import "google/protobuf/struct.proto";

message UserDetailsRequestC {
    string Userid = 1;
    google.protobuf.Struct Properties = 2;
}

message UserDetailsResponse {
    string Userid = 1;
    string PropertiesJSON = 2;
}

service GreeterService {
    rpc SayHelloC (UserDetailsRequestC) returns (UserDetailsResponse) {}
}
```

Server:
```go
package main

import (
	"context"
	"log"
	"net"

	"github.com/bojand/jsonpbtest/pbtypes"
	"github.com/golang/protobuf/jsonpb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

const (
	port = ":50051"
)

func main() {
	runServer()
}

type server struct{}

func (s *server) SayHelloC(ctx context.Context, in *pbtypes.UserDetailsRequestC) (*pbtypes.UserDetailsResponse, error) {
	userID := in.GetUserid()
	props := in.GetProperties()
	propsJSON := ""
	if props != nil {
		ma := jsonpb.Marshaler{}
		out, err := ma.MarshalToString(props)
		if err != nil {
			log.Fatalln("Failed to encode user data:", err)
		}
		propsJSON = out
	}

	log.Printf("IN USER PROPS:\n%+s", propsJSON)

	return &pbtypes.UserDetailsResponse{
		Userid:         userID,
		PropertiesJSON: propsJSON,
	}, nil
}

func runServer() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	s := grpc.NewServer()
	pbtypes.RegisterGreeterServiceServer(s, &server{})

	// Register reflection service on gRPC server.
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

```
/ghz -insecure -proto userdetails.proto -call pbtypes.GreeterService.SayHelloC -d '{"Userid":"userC","Properties":{"foo":"bar","size":11,"nested":{"prop":true}}}' 0.0.0.0:50051

Summary:
  Count:	200
  Total:	15.42 ms
  Slowest:	7.82 ms
  Fastest:	0.49 ms
  Average:	2.74 ms
  Requests/sec:	12966.98

Response time histogram:
  0.492 [1]	|∎
  1.225 [30]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1.957 [33]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  2.690 [34]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  3.423 [56]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  4.156 [20]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  4.889 [12]	|∎∎∎∎∎∎∎∎∎
  5.622 [5]	|∎∎∎∎
  6.355 [3]	|∎∎
  7.088 [3]	|∎∎
  7.821 [3]	|∎∎

Latency distribution:
  10% in 1.00 ms
  25% in 1.55 ms
  50% in 2.71 ms
  75% in 3.37 ms
  90% in 4.46 ms
  95% in 5.36 ms
  99% in 7.72 ms
Status code distribution:
  [OK]	200 responses
```

**Comment by anuj3918** [comment]
Hey Bojan,

Thank you for your response. Yes I think if I use "google.protobuf.Struct"
in my protobuf file, it will incorporate the JSON automatically.

Best Regards,
Anuj

**Pull request closed without merging**
